include:
  - board: nice_nano
    shield: lopro_cosmos_left
  - board: nice_nano
    shield: lopro_cosmos_right
  - board: nice_nano
    shield: lopro_cosmos_left_peripheral
  - board: nice_nano
    shield: settings_reset
