include:
  # 🩻 Left peripheral
  - board: nice_nano_v2
    shield: lopro_cosmos_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  # 🩻 Right peripheral
  - board: nice_nano_v2
    shield: lopro_cosmos_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  # 📡 Central dongle (Uses Studio over USB and UART for split comms)
  - board: nice_nano_v2
    shield: lopro_cosmos_central
    snippet: studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_SPLIT=y
      -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
      -DCONFIG_ZMK_USB=y
      -DCONFIG_ZMK_SPLIT_BLE=n

  # 🔄 Settings reset (for clearing Bluetooth bonds)
  - board: nice_nano_v2
    shield: settings_reset