include:
  - board: nice_nano
    shield: ghidorah_middle
  - board: nice_nano
    shield: ghidorah_right
  - board: nice_nano
    shield: ghidorah_kevin
  - board: nice_nano
    shield: settings_reset

